const UserIconsMap: { [key: number]: string } = {
  1: require("@/assets/images/user_icons/1.png"),
  2: require("@/assets/images/user_icons/2.png"),
  3: require("@/assets/images/user_icons/3.png"),
  4: require("@/assets/images/user_icons/4.png"),
  5: require("@/assets/images/user_icons/5.png"),
  6: require("@/assets/images/user_icons/6.png"),
  7: require("@/assets/images/user_icons/7.png"),
  8: require("@/assets/images/user_icons/8.png"),
  9: require("@/assets/images/user_icons/9.png"),
  10: require("@/assets/images/user_icons/10.png"),
  11: require("@/assets/images/user_icons/11.png"),
  12: require("@/assets/images/user_icons/12.png"),
  13: require("@/assets/images/user_icons/13.png"),
  14: require("@/assets/images/user_icons/14.png"),
  15: require("@/assets/images/user_icons/15.png"),
  16: require("@/assets/images/user_icons/16.png"),
  17: require("@/assets/images/user_icons/17.png"),
  18: require("@/assets/images/user_icons/18.png"),
  19: require("@/assets/images/user_icons/19.png"),
  20: require("@/assets/images/user_icons/20.png"),
  21: require("@/assets/images/user_icons/21.png"),
};
export const letterMapper: { [key: string]: number } = {
  א: 1,
  ב: 2,
  ג: 3,
  ד: 4,
  ה: 5,
  ו: 6,
  ז: 7,
  ח: 8,
  ט: 9,
  י: 10,
  כ: 11,
  ל: 12,
  מ: 13,
  נ: 14,
  ס: 15,
  ע: 16,
  פ: 17,
  ק: 18,
  ר: 19,
  ש: 20,
  ת: 21,
};
export default UserIconsMap;
